theme = "areyouin-land"
baseurl = "https://www.areyouin.es/"
title = "AreYouIN: Queda con tus amigos y conoce gente nueva"
languageCode = "es-ES"
contentdir = "content/es"
publishdir = "public/es"

[params]
    locale = "es-ES"
