theme = "areyouin-land"
baseurl = "https://www.areyouin.io/"
title = "AreYouIN: Hang out with friends and meet new people"
languageCode = "en"
contentdir = "content/en"
publishdir = "public/en"

[params]
    locale = "en"
