theme = "areyouin-land"
baseurl = "http://localhost:8080/"
title = "AreYouIN: Hang out with friends and meet new people"
languageCode = "en"
contentdir = "content/en"
publishdir = "public"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "home"]

[params]
    locale = "en"

[markup.goldmark.renderer]
    unsafe= true
